"use client";
import { UserContextProvider } from "@/context/UserContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [id, setid] = useState("");
  const [username, setusername] = useState("");
  const [email, setemail] = useState("");
  useEffect(() => {
    const getDetails = async () => {
      try {
        const res = await axios.get("/api/users/user");
        setid(res.data.data._id);
        setusername(res.data.data.username);
        setemail(res.data.data.email);
      } catch (error: any) {
        console.log(error.message);
      }
    };
    getDetails();
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider
          value={{ id, setid, username, setusername, email, setemail }}
        >
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
